server:
  port: 80
person:
  name: zhangsan
  age: 18

#DB Configuration:
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    #password:
#spring集成Mybatis环境
mybatis:
  #pojo别名扫描包
  type-aliases-package: com.wcx.entity
  #加载Mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml



